networks:
  tsdproxy_net:
    external: true 
    name: tsdproxy_net
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.8.0 # 
    container_name: mealie
    restart: always
    networks:
      - tsdproxy_net
    ports:
        - "9925:9000" # 
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - ${MEALIE_DATA}:/app/data/
    labels:
      tsdproxy.enable: true
      tsdproxy.container_port: "9000"
      tsdproxy.name: "mealie"
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 568
      PGID: 568
      TZ: Asia/Kolkata
      BASE_URL: https://mealie.mango-catla.ts.net
